import { format } from "date-fns";
import { COMPANY_INFO, generateFilename, downloadFile } from "./exportShared";

interface TaxDeadline {
  id: string;
  title: string;
  date: Date;
  type: "vat" | "cit" | "pit" | "paye" | "wht" | "other";
  description?: string;
  isRecurring?: boolean;
}

export const exportTaxCalendarICS = (deadlines: TaxDeadline[]) => {
  const now = new Date();
  const timestamp = format(now, "yyyyMMdd'T'HHmmss'Z'");
  
  let icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    `PRODID:-//${COMPANY_INFO.shortName}//Tax Calendar//EN`,
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${COMPANY_INFO.shortName} Tax Calendar`,
    `X-WR-TIMEZONE:Africa/Lagos`,
  ].join('\r\n');

  deadlines.forEach((deadline) => {
    const dateStr = format(deadline.date, "yyyyMMdd");
    const uid = `${deadline.id}-${dateStr}@${COMPANY_INFO.website.replace('www.', '')}`;
    
    // Get type label for category
    const typeLabels: Record<string, string> = {
      vat: 'VAT',
      cit: 'Company Income Tax',
      pit: 'Personal Income Tax',
      paye: 'PAYE',
      wht: 'Withholding Tax',
      other: 'Tax',
    };
    
    const category = typeLabels[deadline.type] || 'Tax';
    const description = [
      deadline.description || `${category} deadline`,
      '',
      `Type: ${category}`,
      deadline.isRecurring ? 'This is a recurring deadline.' : '',
      '',
      `Generated by ${COMPANY_INFO.shortName}`,
      COMPANY_INFO.liveUrl,
    ].filter(Boolean).join('\\n');

    icsContent += '\r\n' + [
      'BEGIN:VEVENT',
      `UID:${uid}`,
      `DTSTAMP:${timestamp}`,
      `DTSTART;VALUE=DATE:${dateStr}`,
      `DTEND;VALUE=DATE:${dateStr}`,
      `SUMMARY:${deadline.title}`,
      `DESCRIPTION:${description}`,
      `CATEGORIES:${category}`,
      'STATUS:CONFIRMED',
      'TRANSP:TRANSPARENT',
      // Add reminder 3 days before
      'BEGIN:VALARM',
      'TRIGGER:-P3D',
      'ACTION:DISPLAY',
      `DESCRIPTION:Reminder: ${deadline.title} is due in 3 days`,
      'END:VALARM',
      // Add reminder 1 day before
      'BEGIN:VALARM',
      'TRIGGER:-P1D',
      'ACTION:DISPLAY',
      `DESCRIPTION:Reminder: ${deadline.title} is due tomorrow`,
      'END:VALARM',
      'END:VEVENT',
    ].join('\r\n');
  });

  icsContent += '\r\nEND:VCALENDAR';

  const filename = generateFilename('tax-calendar', 'ics');
  downloadFile(icsContent, filename, 'text/calendar;charset=utf-8');
  
  return filename;
};
